version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j0r4h1b2
      - REPOSITORY_URI=501886171881.dkr.ecr.us-east-1.amazonaws.com/nodejs-repo-ecr
      - docker --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nodejs-ecr .
      - echo Build successful 
      - docker tag nodejs-ecr:latest public.ecr.aws/j0r4h1b2/nodejs-ecr:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker images
      - docker push public.ecr.aws/j0r4h1b2/nodejs-ecr:latest
      - printf '[{"name":"nodejs-container","imageUri":"%s"}]' 501886171881.dkr.ecr.us-east-1.amazonaws.com/nodejs-repo-ecr > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json
