version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=501886171881.dkr.ecr.us-east-1.amazonaws.com/nodejs-repo-ecr
      - docker --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nodejs-repo-ecr:latest .
      - echo Build successful 
      - docker tag nodejs-repo-ecr:latest 501886171881.dkr.ecr.us-east-1.amazonaws.com/nodejs-repo-ecr
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker images
      - docker push 501886171881.dkr.ecr.us-east-1.amazonaws.com/nodejs-repo-ecr
      - printf '[{"name":"nodejs-container","imageUri":"%s"}]' 501886171881.dkr.ecr.us-east-1.amazonaws.com/nodejs-repo-ecr > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json
